### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by bede** [GlobalPathogenAnalysisService/gpas-cli#6]
- [ ] #8
- [ ] #9
- [ ] #10
- [ ] #11
- [ ] #12
- [ ] #13
- [ ] #14
- [ ] #15
- [x] #16
- [ ] #17
- [ ] #18
- [x] #19

**Docs**
- [ ] CLI
- [ ] API
- [ ] Electron client interface (JSON over stdout)

**Testing**

- [ ] Upload system tests
- [ ] Unit testing of validation checks
- [ ] Port test cases from gpas-uploader
